kind: pipeline
name: automatic-testing

steps:
  - name: restore-cache
    image: golang
    volumes:
      - name: cache
        path: /cache
    commands:
      - git rev-parse --short HEAD
      - mkdir -p /cache/exponential-backoff-retry/node_modules
      - cp -Rf /cache/exponential-backoff-retry/node_modules/ node_modules/
    depends_on: [ clone ]

  - name: npm-update
    image: node:12.13.0
    commands:
      - npm install
    depends_on: [ restore-cache ]

  - name: eslint-server
    image: node:12.13.0
    commands:
      - node_modules/eslint/bin/eslint.js  --ext .ts src
    depends_on: [ npm-update ]

  - name: tslint
    image: node:12.13.0
    commands:
      - node_modules/tslint/bin/tslint -p ./ -c src/tslint.json
      - node_modules/typescript/bin/tsc -p ./
      - rm -r dist
    depends_on: [ npm-update ]

  - name: test-server
    image: node:12.13.0
    privileged: true
    commands:
      - node_modules/.bin/nyc node_modules/.bin/mocha./**/*.spec.ts --exit
      - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov;
    depends_on: [ eslint-server, tslint ]

  - name: build-cache
    image: golang
    volumes:
      - name: cache
        path: /cache
    commands:
      - cp -Rf node_modules/ /cache/exponential-backoff-retry/
    depends_on: [ test-server ]

volumes:
  - name: cache
    host:
      path: /home/ubuntu/cureskin/live/drone/cache
